#!/usr/bin/env python3
import argparse
import os

program_description = 'Make a new submission according to the latest contest template.'

def handle_input():
    parser = argparse.ArgumentParser(description=program_description)
    parser.add_argument( \
            '--name', \
            help='"Matt Laine"', \
            type=str, \
            required=True, \
            )
    parser.add_argument( \
            '--email', \
            help='"matt@brain-fuel.co"', \
            type=str, \
            required=True, \
            )
    parser.add_argument( \
            '--title', \
            help='"Radix Sort"', \
            type=str, \
            required=True, \
            )
    return parser.parse_args()

def print_blank_line():
    print('')

def print_parsed_args(prog_input):
    print('You Entered:')
    print_blank_line()
    print('   Name:  ' + prog_input.name)
    print('   Email: ' + prog_input.email)
    print('   Title: ' + prog_input.title)
    print_blank_line()

def folder_name_from_input(prog_input) -> str:
    hyphenated_title = prog_input.title.lower().replace(' ','-')
    hyphenated_name = prog_input.name.lower().replace(' ','-')
    return hyphenated_title + '-' + hyphenated_name

def make_folder(folder_name) -> bool:
    if os.path.isdir(folder_name):
        return False
    else:
        os.mkdir(folder_name)
        return True

def print_whether_folder_made(folder_name: str, made_folder: bool):
    if made_folder:
        print("Made folder: " + folder_name)
    else:
        print("Folder " + folder_name + " already exists.")

def submission_content_stub_from_input(prog_input) -> str:
    print('submission_content_stub_from_input function still needs work')

def main():
    prog_input = handle_input()
    print_blank_line()
    print_parsed_args(prog_input)
    folder_name = folder_name_from_input(prog_input)
    made_folder = make_folder(folder_name)
    print_whether_folder_made(folder_name, made_folder)
    print_blank_line()
    submission_content_stub = submission_content_stub_from_input(prog_input)
    print_blank_line()

main()
